- name: set up environment
  hosts: drogon.eastus.cloudapp.azure.com
  become: yes
  tasks:
    - name: install docker
      apt:
        name:
          - docker
          - docker-compose
        state: present

    - name: Start service docker if not started
      service:
        name: docker
        state: started
    - name: build phase
      shell:
          cmd: docker-compose up -d

#     - name: copy files
#       ansible.builtin.copy:
#       src: $(build.artifactstagingdirectory)
#       dest: /home/azureuser/
#       owner: "{{ ansible_user }}"
#       group: "{{ ansible_user }}"
#       mode: "0777"



