- name: set up environment
  hosts: all
  become: yes
  tasks:
    - name: install docker
      apt:
        name: 
          - docker
          - docker-compose
        state: present

    - name: Start service docker if not started
      service:
        name: docker
        state: started
    - name: copy files
      ansible.builtin.copy:
      src: $(build.artifactstagingdirectory)
      dest: /home/azureuser/
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: "0777"
=======
#     - name: copy files
#       ansible.builtin.copy:
#       src: $(build.artifactstagingdirectory)
#       dest: /home/azureuser/
#       owner: "{{ ansible_user }}"
#       group: "{{ ansible_user }}"
#       mode: "0777"
>>>>>>> e0077d457ffec2b64479382c1c31b608eabdb4e0

    - name: deploy Docker Compose stack
      community.docker.docker_compose:
      project_src: /home/azureuser/


